# Generated by Django 4.2.4 on 2023-08-29 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_department_usersinfo_delete_userinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='manager',
        ),
    ]
