# Generated by Django 4.2.4 on 2023-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_filebank'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket',
            field=models.CharField(default=111, max_length=128, verbose_name='存储桶'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='bucket_region',
            field=models.CharField(default=222, max_length=32, verbose_name='存储桶区域'),
            preserve_default=False,
        ),
    ]
