# Generated by Django 4.2.4 on 2023-09-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0007_module_issuestype_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebank',
            name='name',
            field=models.CharField(help_text='文件/文件夹名', max_length=128, verbose_name='文件夹名称'),
        ),
    ]
