# Generated by Django 4.2.4 on 2023-09-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0008_alter_filebank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.module', verbose_name='模块'),
        ),
    ]
