# Generated by Django 4.2.4 on 2023-09-18 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0009_alter_issues_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuesReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_type', models.SmallIntegerField(choices=[(1, '修改记录'), (2, '回复')], verbose_name='')),
                ('content', models.TextField(verbose_name='')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_reply', to='saas.users')),
                ('issues', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.issues', verbose_name='')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.issuesreply')),
            ],
        ),
    ]
